Repository carbynestack/carbynestack.github.io, pull requests merged in 2022-04, with the labels that each got.

#44 Add OSS analytics JD
  .pre-commit-config.yaml
  docs/community/opportunities.md
Labels: documentation

#43 Links to discord server and community meetings
  config/nav.yml
  docs/community/participate.md
  overrides/assets/stylesheets/home.css
  overrides/home.html
Labels: documentation

#47 Ignore all local and private IP ranges for analytics
  overrides/main.html
Labels: enhancement

#48 Add installation instructions of prerequisites
  config/nav.yml
  docs/getting-started/prerequisites.md
Labels: documentation

#46 Add page enumerating CS related events
  config/nav.yml
  docs/community/events.md
  docs/images/events/bocse22.png
  docs/images/events/stackconf22.png
  docs/images/events/tpmpc22.png
  docs/stylesheets/extra.css
Labels: documentation

#51 Various updates
  config/nav.yml
  docs/community/acknowledgements.md
  docs/community/events.md
  docs/images/bmbf-logo.svg
  docs/images/events/ossna22.svg
  docs/stylesheets/extra.css
  overrides/assets/stylesheets/home.css
  overrides/home.html
  overrides/main.html
Labels: documentation, enhancement
